name: .NET Unit Tests

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unit-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Install Playwright
      run: pwsh tests/Test.UI/bin/Debug/net8.0/playwright.ps1 install
    
    - name: Build solution
      run: dotnet build --no-restore --configuration Release

    - name: Run Unit Tests (Category=UnitTest)
      run: dotnet test --no-build --configuration Release --filter "TestCategory=UnitTest"
